version: '3'

services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_DB: onlyoffice_pipedrive
      POSTGRES_USER: onlyoffice
      POSTGRES_PASSWORD: onlyoffice
    ports:
      - "5432:5432"
